packages:
  - apps/*
  - packages/*

allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  msw: false
  protobufjs: true
  sharp: true

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - msw

onlyBuiltDependencies:
  - esbuild
  - sharp
