packages:
  - apps/*
  - packages/*

allowBuilds:
  '@alicloud/openapi-core': true
  '@biomejs/biome': true
  esbuild: true
  msw: false
  protobufjs: true
  sharp: true

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - msw

onlyBuiltDependencies:
  - '@alicloud/openapi-core'
  - esbuild
  - sharp
