"use client";
import { useCallback } from "react";
import { AdminView } from "./admin-view";
import { fetchAdminOverview } from "@/lib/admin-api";

const actionLabels: Record<string,string>={"user.balance.adjusted":"调整用户余额","model.price.updated":"更新模型定价","plan.updated":"更新订阅套餐","provider.updated":"更新供应商配置"};
const resourceLabels: Record<string,string>={model:"模型",plan:"套餐",provider:"供应商"};
function AuditTarget({audit}:{audit:any}){if(audit.targetUser)return <div className="text-muted-foreground"><p>用户：{audit.targetUser.displayName||"未设置昵称"}</p><p>邮箱：{audit.targetUser.email}</p><p className="break-all">用户 ID：{audit.targetUser.id}</p></div>;return <span className="break-all text-muted-foreground">{audit.resourceType==="user"?"用户 ID":resourceLabels[audit.resourceType]??"目标"}：{audit.resourceId}</span>}
export default function AdminPage(){const load=useCallback(fetchAdminOverview,[]);return <AdminView title="运营概览" load={load}>{(d:any)=><><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["累计收入",`¥${(d.metrics.revenueFen/100).toLocaleString("zh-CN",{minimumFractionDigits:2})}`],["累计退款",`¥${(d.metrics.refundFen/100).toFixed(2)}`],["生成次数",d.metrics.generationCount],["活跃用户",d.metrics.activeUsers]].map(([k,v])=><div key={k} className="rounded-md border bg-background p-4"><p className="text-xs text-muted-foreground">{k}</p><p className="mt-2 text-2xl font-semibold">{v}</p></div>)}</div><div className="mt-6 overflow-hidden rounded-md border bg-background"><div className="border-b px-4 py-3 text-sm font-medium">最近操作记录</div>{d.recentAudit.length?d.recentAudit.map((a:any)=><div key={a.id} className="grid gap-2 border-b px-4 py-3 text-sm last:border-0 sm:grid-cols-[1fr_1.2fr_2fr_auto]"><span className="font-medium">{actionLabels[a.action]??"后台操作"}</span><span className="text-muted-foreground">操作人：{a.actorEmail}</span><AuditTarget audit={a}/><time className="text-muted-foreground" dateTime={a.createdAt}>{new Date(a.createdAt).toLocaleString("zh-CN",{hour12:false})}</time></div>):<p className="p-4 text-sm text-muted-foreground">暂时没有操作记录。</p>}</div></>}</AdminView>}
